// Generated by gir (https://github.com/gtk-rs/gir @ 5d24c2e70796)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 4022f0145e94)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) BIS_ALBUM_TRANSITION_TYPE_OVER);
    PRINT_CONSTANT((gint) BIS_ALBUM_TRANSITION_TYPE_SLIDE);
    PRINT_CONSTANT((gint) BIS_ALBUM_TRANSITION_TYPE_UNDER);
    PRINT_CONSTANT((gint) BIS_ANIMATION_FINISHED);
    PRINT_CONSTANT((gint) BIS_ANIMATION_IDLE);
    PRINT_CONSTANT((gint) BIS_ANIMATION_PAUSED);
    PRINT_CONSTANT((gint) BIS_ANIMATION_PLAYING);
    PRINT_CONSTANT(BIS_DURATION_INFINITE);
    PRINT_CONSTANT((gint) BIS_EASE_IN_BACK);
    PRINT_CONSTANT((gint) BIS_EASE_IN_BOUNCE);
    PRINT_CONSTANT((gint) BIS_EASE_IN_CIRC);
    PRINT_CONSTANT((gint) BIS_EASE_IN_CUBIC);
    PRINT_CONSTANT((gint) BIS_EASE_IN_ELASTIC);
    PRINT_CONSTANT((gint) BIS_EASE_IN_EXPO);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_BACK);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_BOUNCE);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_CIRC);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_CUBIC);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_ELASTIC);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_EXPO);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_QUAD);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_QUART);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_QUINT);
    PRINT_CONSTANT((gint) BIS_EASE_IN_OUT_SINE);
    PRINT_CONSTANT((gint) BIS_EASE_IN_QUAD);
    PRINT_CONSTANT((gint) BIS_EASE_IN_QUART);
    PRINT_CONSTANT((gint) BIS_EASE_IN_QUINT);
    PRINT_CONSTANT((gint) BIS_EASE_IN_SINE);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_BACK);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_BOUNCE);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_CIRC);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_CUBIC);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_ELASTIC);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_EXPO);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_QUAD);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_QUART);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_QUINT);
    PRINT_CONSTANT((gint) BIS_EASE_OUT_SINE);
    PRINT_CONSTANT((gint) BIS_FOLD_THRESHOLD_POLICY_MINIMUM);
    PRINT_CONSTANT((gint) BIS_FOLD_THRESHOLD_POLICY_NATURAL);
    PRINT_CONSTANT((gint) BIS_HUGGER_TRANSITION_TYPE_CROSSFADE);
    PRINT_CONSTANT((gint) BIS_HUGGER_TRANSITION_TYPE_NONE);
    PRINT_CONSTANT((gint) BIS_LAPEL_FOLD_POLICY_ALWAYS);
    PRINT_CONSTANT((gint) BIS_LAPEL_FOLD_POLICY_AUTO);
    PRINT_CONSTANT((gint) BIS_LAPEL_FOLD_POLICY_NEVER);
    PRINT_CONSTANT((gint) BIS_LAPEL_TRANSITION_TYPE_OVER);
    PRINT_CONSTANT((gint) BIS_LAPEL_TRANSITION_TYPE_SLIDE);
    PRINT_CONSTANT((gint) BIS_LAPEL_TRANSITION_TYPE_UNDER);
    PRINT_CONSTANT((gint) BIS_LINEAR);
    PRINT_CONSTANT(BIS_MAJOR_VERSION);
    PRINT_CONSTANT(BIS_MICRO_VERSION);
    PRINT_CONSTANT(BIS_MINOR_VERSION);
    PRINT_CONSTANT((gint) BIS_NAVIGATION_DIRECTION_BACK);
    PRINT_CONSTANT((gint) BIS_NAVIGATION_DIRECTION_FORWARD);
    PRINT_CONSTANT(BIS_VERSION_S);
    return 0;
}
