// Generated by gir (https://github.com/gtk-rs/gir @ 3fcec321a85e)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ a368f925fd3c)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) FUSEBOX_FUSE_CATEGORY_CUSTOM);
    PRINT_CONSTANT((gint) FUSEBOX_FUSE_CATEGORY_NETWORK);
    PRINT_CONSTANT((gint) FUSEBOX_FUSE_CATEGORY_PERSONAL);
    PRINT_CONSTANT((gint) FUSEBOX_FUSE_CATEGORY_SYSTEM);
    return 0;
}
