// Generated by gir (https://github.com/gtk-rs/gir @ 68044d02c2a3)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 5245759fdac8)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "FuseboxFuse", sizeof(FuseboxFuse), alignof(FuseboxFuse));
    printf("%s;%zu;%zu\n", "FuseboxFuseCategory", sizeof(FuseboxFuseCategory), alignof(FuseboxFuseCategory));
    printf("%s;%zu;%zu\n", "FuseboxFuseClass", sizeof(FuseboxFuseClass), alignof(FuseboxFuseClass));
    printf("%s;%zu;%zu\n", "FuseboxFusesManager", sizeof(FuseboxFusesManager), alignof(FuseboxFusesManager));
    printf("%s;%zu;%zu\n", "FuseboxFusesManagerClass", sizeof(FuseboxFusesManagerClass), alignof(FuseboxFusesManagerClass));
    return 0;
}
