// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

mod fuse;
pub use self::fuse::Fuse;

mod fuses_manager;
pub use self::fuses_manager::FusesManager;

mod enums;
pub use self::enums::FuseCategory;

#[doc(hidden)]
pub mod traits {
    pub use super::fuse::FuseExt;
    pub use super::fuses_manager::FusesManagerExt;
}
