// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files
// DO NOT EDIT

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ColorXYZColor(Boxed<ffi::HeColorXYZColor>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::he_color_xyz_color_get_type(), ptr as *mut _) as *mut ffi::HeColorXYZColor,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::he_color_xyz_color_get_type(), ptr as *mut _),
        type_ => || ffi::he_color_xyz_color_get_type(),
    }
}
