// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct LABColor(Boxed<ffi::HeLABColor>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::he_lab_color_get_type(), ptr as *mut _) as *mut ffi::HeLABColor,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::he_lab_color_get_type(), ptr as *mut _),
        type_ => || ffi::he_lab_color_get_type(),
    }
}

impl LABColor {
    #[doc(alias = "he_lab_color_distance")]
    pub fn distance(&mut self, lab: &mut LABColor) -> f64 {
        unsafe { ffi::he_lab_color_distance(self.to_glib_none_mut().0, lab.to_glib_none_mut().0) }
    }
}
