// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files
// DO NOT EDIT

use crate::{Bin, Colors, OverlayButtonAlignment, OverlayButtonSize};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::{boxed::Box as Box_, fmt, mem::transmute};

glib::wrapper! {
    #[doc(alias = "HeOverlayButton")]
    pub struct OverlayButton(Object<ffi::HeOverlayButton, ffi::HeOverlayButtonClass>) @extends Bin, gtk::Widget, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::he_overlay_button_get_type(),
    }
}

impl OverlayButton {
    pub const NONE: Option<&'static OverlayButton> = None;

    #[doc(alias = "he_overlay_button_new")]
    pub fn new(icon: &str, label: Option<&str>, secondary_icon: Option<&str>) -> OverlayButton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::he_overlay_button_new(
                icon.to_glib_none().0,
                label.to_glib_none().0,
                secondary_icon.to_glib_none().0,
            ))
        }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`OverlayButton`] objects.
    ///
    /// This method returns an instance of [`OverlayButtonBuilder`](crate::builders::OverlayButtonBuilder) which can be used to create [`OverlayButton`] objects.
    pub fn builder() -> OverlayButtonBuilder {
        OverlayButtonBuilder::default()
    }
}

impl Default for OverlayButton {
    fn default() -> Self {
        glib::object::Object::new::<Self>(&[])
    }
}

#[derive(Clone, Default)]
// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`OverlayButton`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct OverlayButtonBuilder {
    size: Option<OverlayButtonSize>,
    color: Option<Colors>,
    secondary_color: Option<Colors>,
    secondary_icon: Option<String>,
    icon: Option<String>,
    label: Option<String>,
    child: Option<gtk::Widget>,
    alignment: Option<OverlayButtonAlignment>,
    can_focus: Option<bool>,
    can_target: Option<bool>,
    css_classes: Option<Vec<String>>,
    css_name: Option<String>,
    //cursor: /*Unknown type*/,
    focus_on_click: Option<bool>,
    focusable: Option<bool>,
    halign: Option<gtk::Align>,
    has_tooltip: Option<bool>,
    height_request: Option<i32>,
    hexpand: Option<bool>,
    hexpand_set: Option<bool>,
    //layout-manager: /*Unknown type*/,
    margin_bottom: Option<i32>,
    margin_end: Option<i32>,
    margin_start: Option<i32>,
    margin_top: Option<i32>,
    name: Option<String>,
    opacity: Option<f64>,
    //overflow: /*Unknown type*/,
    receives_default: Option<bool>,
    sensitive: Option<bool>,
    tooltip_markup: Option<String>,
    tooltip_text: Option<String>,
    valign: Option<gtk::Align>,
    vexpand: Option<bool>,
    vexpand_set: Option<bool>,
    visible: Option<bool>,
    width_request: Option<i32>,
    //accessible-role: /*Unknown type*/,
}

impl OverlayButtonBuilder {
    // rustdoc-stripper-ignore-next
    /// Create a new [`OverlayButtonBuilder`].
    pub fn new() -> Self {
        Self::default()
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`OverlayButton`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> OverlayButton {
        let mut properties: Vec<(&str, &dyn ToValue)> = vec![];
        if let Some(ref size) = self.size {
            properties.push(("size", size));
        }
        if let Some(ref color) = self.color {
            properties.push(("color", color));
        }
        if let Some(ref secondary_color) = self.secondary_color {
            properties.push(("secondary-color", secondary_color));
        }
        if let Some(ref secondary_icon) = self.secondary_icon {
            properties.push(("secondary-icon", secondary_icon));
        }
        if let Some(ref icon) = self.icon {
            properties.push(("icon", icon));
        }
        if let Some(ref label) = self.label {
            properties.push(("label", label));
        }
        if let Some(ref child) = self.child {
            properties.push(("child", child));
        }
        if let Some(ref alignment) = self.alignment {
            properties.push(("alignment", alignment));
        }
        if let Some(ref can_focus) = self.can_focus {
            properties.push(("can-focus", can_focus));
        }
        if let Some(ref can_target) = self.can_target {
            properties.push(("can-target", can_target));
        }
        if let Some(ref css_classes) = self.css_classes {
            properties.push(("css-classes", css_classes));
        }
        if let Some(ref css_name) = self.css_name {
            properties.push(("css-name", css_name));
        }
        if let Some(ref focus_on_click) = self.focus_on_click {
            properties.push(("focus-on-click", focus_on_click));
        }
        if let Some(ref focusable) = self.focusable {
            properties.push(("focusable", focusable));
        }
        if let Some(ref halign) = self.halign {
            properties.push(("halign", halign));
        }
        if let Some(ref has_tooltip) = self.has_tooltip {
            properties.push(("has-tooltip", has_tooltip));
        }
        if let Some(ref height_request) = self.height_request {
            properties.push(("height-request", height_request));
        }
        if let Some(ref hexpand) = self.hexpand {
            properties.push(("hexpand", hexpand));
        }
        if let Some(ref hexpand_set) = self.hexpand_set {
            properties.push(("hexpand-set", hexpand_set));
        }
        if let Some(ref margin_bottom) = self.margin_bottom {
            properties.push(("margin-bottom", margin_bottom));
        }
        if let Some(ref margin_end) = self.margin_end {
            properties.push(("margin-end", margin_end));
        }
        if let Some(ref margin_start) = self.margin_start {
            properties.push(("margin-start", margin_start));
        }
        if let Some(ref margin_top) = self.margin_top {
            properties.push(("margin-top", margin_top));
        }
        if let Some(ref name) = self.name {
            properties.push(("name", name));
        }
        if let Some(ref opacity) = self.opacity {
            properties.push(("opacity", opacity));
        }
        if let Some(ref receives_default) = self.receives_default {
            properties.push(("receives-default", receives_default));
        }
        if let Some(ref sensitive) = self.sensitive {
            properties.push(("sensitive", sensitive));
        }
        if let Some(ref tooltip_markup) = self.tooltip_markup {
            properties.push(("tooltip-markup", tooltip_markup));
        }
        if let Some(ref tooltip_text) = self.tooltip_text {
            properties.push(("tooltip-text", tooltip_text));
        }
        if let Some(ref valign) = self.valign {
            properties.push(("valign", valign));
        }
        if let Some(ref vexpand) = self.vexpand {
            properties.push(("vexpand", vexpand));
        }
        if let Some(ref vexpand_set) = self.vexpand_set {
            properties.push(("vexpand-set", vexpand_set));
        }
        if let Some(ref visible) = self.visible {
            properties.push(("visible", visible));
        }
        if let Some(ref width_request) = self.width_request {
            properties.push(("width-request", width_request));
        }
        glib::Object::new::<OverlayButton>(&properties)
    }

    pub fn size(mut self, size: OverlayButtonSize) -> Self {
        self.size = Some(size);
        self
    }

    pub fn color(mut self, color: Colors) -> Self {
        self.color = Some(color);
        self
    }

    pub fn secondary_color(mut self, secondary_color: Colors) -> Self {
        self.secondary_color = Some(secondary_color);
        self
    }

    pub fn secondary_icon(mut self, secondary_icon: &str) -> Self {
        self.secondary_icon = Some(secondary_icon.to_string());
        self
    }

    pub fn icon(mut self, icon: &str) -> Self {
        self.icon = Some(icon.to_string());
        self
    }

    pub fn label(mut self, label: &str) -> Self {
        self.label = Some(label.to_string());
        self
    }

    pub fn child(mut self, child: &impl IsA<gtk::Widget>) -> Self {
        self.child = Some(child.clone().upcast());
        self
    }

    pub fn alignment(mut self, alignment: OverlayButtonAlignment) -> Self {
        self.alignment = Some(alignment);
        self
    }

    pub fn can_focus(mut self, can_focus: bool) -> Self {
        self.can_focus = Some(can_focus);
        self
    }

    pub fn can_target(mut self, can_target: bool) -> Self {
        self.can_target = Some(can_target);
        self
    }

    pub fn css_classes(mut self, css_classes: Vec<String>) -> Self {
        self.css_classes = Some(css_classes);
        self
    }

    pub fn css_name(mut self, css_name: &str) -> Self {
        self.css_name = Some(css_name.to_string());
        self
    }

    pub fn focus_on_click(mut self, focus_on_click: bool) -> Self {
        self.focus_on_click = Some(focus_on_click);
        self
    }

    pub fn focusable(mut self, focusable: bool) -> Self {
        self.focusable = Some(focusable);
        self
    }

    pub fn halign(mut self, halign: gtk::Align) -> Self {
        self.halign = Some(halign);
        self
    }

    pub fn has_tooltip(mut self, has_tooltip: bool) -> Self {
        self.has_tooltip = Some(has_tooltip);
        self
    }

    pub fn height_request(mut self, height_request: i32) -> Self {
        self.height_request = Some(height_request);
        self
    }

    pub fn hexpand(mut self, hexpand: bool) -> Self {
        self.hexpand = Some(hexpand);
        self
    }

    pub fn hexpand_set(mut self, hexpand_set: bool) -> Self {
        self.hexpand_set = Some(hexpand_set);
        self
    }

    pub fn margin_bottom(mut self, margin_bottom: i32) -> Self {
        self.margin_bottom = Some(margin_bottom);
        self
    }

    pub fn margin_end(mut self, margin_end: i32) -> Self {
        self.margin_end = Some(margin_end);
        self
    }

    pub fn margin_start(mut self, margin_start: i32) -> Self {
        self.margin_start = Some(margin_start);
        self
    }

    pub fn margin_top(mut self, margin_top: i32) -> Self {
        self.margin_top = Some(margin_top);
        self
    }

    pub fn name(mut self, name: &str) -> Self {
        self.name = Some(name.to_string());
        self
    }

    pub fn opacity(mut self, opacity: f64) -> Self {
        self.opacity = Some(opacity);
        self
    }

    pub fn receives_default(mut self, receives_default: bool) -> Self {
        self.receives_default = Some(receives_default);
        self
    }

    pub fn sensitive(mut self, sensitive: bool) -> Self {
        self.sensitive = Some(sensitive);
        self
    }

    pub fn tooltip_markup(mut self, tooltip_markup: &str) -> Self {
        self.tooltip_markup = Some(tooltip_markup.to_string());
        self
    }

    pub fn tooltip_text(mut self, tooltip_text: &str) -> Self {
        self.tooltip_text = Some(tooltip_text.to_string());
        self
    }

    pub fn valign(mut self, valign: gtk::Align) -> Self {
        self.valign = Some(valign);
        self
    }

    pub fn vexpand(mut self, vexpand: bool) -> Self {
        self.vexpand = Some(vexpand);
        self
    }

    pub fn vexpand_set(mut self, vexpand_set: bool) -> Self {
        self.vexpand_set = Some(vexpand_set);
        self
    }

    pub fn visible(mut self, visible: bool) -> Self {
        self.visible = Some(visible);
        self
    }

    pub fn width_request(mut self, width_request: i32) -> Self {
        self.width_request = Some(width_request);
        self
    }
}

pub trait OverlayButtonExt: 'static {
    #[doc(alias = "he_overlay_button_get_size")]
    #[doc(alias = "get_size")]
    fn size(&self) -> OverlayButtonSize;

    #[doc(alias = "he_overlay_button_set_size")]
    fn set_size(&self, value: OverlayButtonSize);

    #[doc(alias = "he_overlay_button_get_color")]
    #[doc(alias = "get_color")]
    fn color(&self) -> Colors;

    #[doc(alias = "he_overlay_button_set_color")]
    fn set_color(&self, value: Colors);

    #[doc(alias = "he_overlay_button_get_secondary_color")]
    #[doc(alias = "get_secondary_color")]
    fn secondary_color(&self) -> Colors;

    #[doc(alias = "he_overlay_button_set_secondary_color")]
    fn set_secondary_color(&self, value: Colors);

    #[doc(alias = "he_overlay_button_get_secondary_icon")]
    #[doc(alias = "get_secondary_icon")]
    fn secondary_icon(&self) -> Option<glib::GString>;

    #[doc(alias = "he_overlay_button_set_secondary_icon")]
    fn set_secondary_icon(&self, value: Option<&str>);

    #[doc(alias = "he_overlay_button_get_icon")]
    #[doc(alias = "get_icon")]
    fn icon(&self) -> glib::GString;

    #[doc(alias = "he_overlay_button_set_icon")]
    fn set_icon(&self, value: &str);

    #[doc(alias = "he_overlay_button_get_label")]
    #[doc(alias = "get_label")]
    fn label(&self) -> Option<glib::GString>;

    #[doc(alias = "he_overlay_button_set_label")]
    fn set_label(&self, value: Option<&str>);

    #[doc(alias = "he_overlay_button_get_child")]
    #[doc(alias = "get_child")]
    fn child(&self) -> Option<gtk::Widget>;

    #[doc(alias = "he_overlay_button_set_child")]
    fn set_child(&self, value: Option<&impl IsA<gtk::Widget>>);

    #[doc(alias = "he_overlay_button_get_alignment")]
    #[doc(alias = "get_alignment")]
    fn alignment(&self) -> OverlayButtonAlignment;

    #[doc(alias = "he_overlay_button_set_alignment")]
    fn set_alignment(&self, value: OverlayButtonAlignment);

    #[doc(alias = "clicked")]
    fn connect_clicked<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "secondary-clicked")]
    fn connect_secondary_clicked<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "size")]
    fn connect_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "color")]
    fn connect_color_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "secondary-color")]
    fn connect_secondary_color_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "secondary-icon")]
    fn connect_secondary_icon_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "icon")]
    fn connect_icon_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "label")]
    fn connect_label_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "alignment")]
    fn connect_alignment_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<OverlayButton>> OverlayButtonExt for O {
    fn size(&self) -> OverlayButtonSize {
        unsafe {
            from_glib(ffi::he_overlay_button_get_size(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_size(&self, value: OverlayButtonSize) {
        unsafe {
            ffi::he_overlay_button_set_size(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    fn color(&self) -> Colors {
        unsafe {
            from_glib(ffi::he_overlay_button_get_color(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_color(&self, value: Colors) {
        unsafe {
            ffi::he_overlay_button_set_color(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    fn secondary_color(&self) -> Colors {
        unsafe {
            from_glib(ffi::he_overlay_button_get_secondary_color(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_secondary_color(&self, value: Colors) {
        unsafe {
            ffi::he_overlay_button_set_secondary_color(
                self.as_ref().to_glib_none().0,
                value.into_glib(),
            );
        }
    }

    fn secondary_icon(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::he_overlay_button_get_secondary_icon(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_secondary_icon(&self, value: Option<&str>) {
        unsafe {
            ffi::he_overlay_button_set_secondary_icon(
                self.as_ref().to_glib_none().0,
                value.to_glib_none().0,
            );
        }
    }

    fn icon(&self) -> glib::GString {
        unsafe {
            from_glib_full(ffi::he_overlay_button_get_icon(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_icon(&self, value: &str) {
        unsafe {
            ffi::he_overlay_button_set_icon(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn label(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::he_overlay_button_get_label(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_label(&self, value: Option<&str>) {
        unsafe {
            ffi::he_overlay_button_set_label(
                self.as_ref().to_glib_none().0,
                value.to_glib_none().0,
            );
        }
    }

    fn child(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::he_overlay_button_get_child(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_child(&self, value: Option<&impl IsA<gtk::Widget>>) {
        unsafe {
            ffi::he_overlay_button_set_child(
                self.as_ref().to_glib_none().0,
                value.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }

    fn alignment(&self) -> OverlayButtonAlignment {
        unsafe {
            from_glib(ffi::he_overlay_button_get_alignment(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_alignment(&self, value: OverlayButtonAlignment) {
        unsafe {
            ffi::he_overlay_button_set_alignment(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    fn connect_clicked<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn clicked_trampoline<P: IsA<OverlayButton>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeOverlayButton,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"clicked\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    clicked_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_secondary_clicked<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn secondary_clicked_trampoline<
            P: IsA<OverlayButton>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::HeOverlayButton,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"secondary-clicked\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    secondary_clicked_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_size_trampoline<P: IsA<OverlayButton>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::size\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_size_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_color_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_color_trampoline<P: IsA<OverlayButton>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::color\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_color_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_secondary_color_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_secondary_color_trampoline<
            P: IsA<OverlayButton>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::secondary-color\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_secondary_color_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_secondary_icon_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_secondary_icon_trampoline<
            P: IsA<OverlayButton>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::secondary-icon\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_secondary_icon_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_icon_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_icon_trampoline<P: IsA<OverlayButton>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::icon\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_icon_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_label_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_label_trampoline<P: IsA<OverlayButton>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::label\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_label_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_alignment_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_alignment_trampoline<
            P: IsA<OverlayButton>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::HeOverlayButton,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(OverlayButton::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::alignment\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_alignment_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for OverlayButton {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("OverlayButton")
    }
}
