// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::Bin;
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::{boxed::Box as Box_, fmt, mem::transmute};

glib::wrapper! {
    #[doc(alias = "HeTab")]
    pub struct Tab(Object<ffi::HeTab, ffi::HeTabClass>) @extends Bin, gtk::Widget, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::he_tab_get_type(),
    }
}

impl Tab {
    pub const NONE: Option<&'static Tab> = None;

    #[doc(alias = "he_tab_new")]
    pub fn new(label: Option<&str>, page: Option<&impl IsA<gtk::Widget>>) -> Tab {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::he_tab_new(
                label.to_glib_none().0,
                page.map(|p| p.as_ref()).to_glib_none().0,
            ))
        }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Tab`] objects.
    ///
    /// This method returns an instance of [`TabBuilder`](crate::builders::TabBuilder) which can be used to create [`Tab`] objects.
    pub fn builder() -> TabBuilder {
        TabBuilder::default()
    }
}

impl Default for Tab {
    fn default() -> Self {
        glib::object::Object::new::<Self>(&[])
    }
}

#[derive(Clone, Default)]
// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Tab`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct TabBuilder {
    label: Option<String>,
    tooltip: Option<String>,
    pinned: Option<bool>,
    can_pin: Option<bool>,
    can_close: Option<bool>,
    page: Option<gtk::Widget>,
    menu: Option<gio::Menu>,
    actions: Option<gio::SimpleActionGroup>,
    child: Option<gtk::Widget>,
    can_focus: Option<bool>,
    can_target: Option<bool>,
    css_classes: Option<Vec<String>>,
    css_name: Option<String>,
    //cursor: /*Unknown type*/,
    focus_on_click: Option<bool>,
    focusable: Option<bool>,
    halign: Option<gtk::Align>,
    has_tooltip: Option<bool>,
    height_request: Option<i32>,
    hexpand: Option<bool>,
    hexpand_set: Option<bool>,
    //layout-manager: /*Unknown type*/,
    margin_bottom: Option<i32>,
    margin_end: Option<i32>,
    margin_start: Option<i32>,
    margin_top: Option<i32>,
    name: Option<String>,
    opacity: Option<f64>,
    //overflow: /*Unknown type*/,
    receives_default: Option<bool>,
    sensitive: Option<bool>,
    tooltip_markup: Option<String>,
    tooltip_text: Option<String>,
    valign: Option<gtk::Align>,
    vexpand: Option<bool>,
    vexpand_set: Option<bool>,
    visible: Option<bool>,
    width_request: Option<i32>,
    //accessible-role: /*Unknown type*/,
}

impl TabBuilder {
    // rustdoc-stripper-ignore-next
    /// Create a new [`TabBuilder`].
    pub fn new() -> Self {
        Self::default()
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Tab`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Tab {
        let mut properties: Vec<(&str, &dyn ToValue)> = vec![];
        if let Some(ref label) = self.label {
            properties.push(("label", label));
        }
        if let Some(ref tooltip) = self.tooltip {
            properties.push(("tooltip", tooltip));
        }
        if let Some(ref pinned) = self.pinned {
            properties.push(("pinned", pinned));
        }
        if let Some(ref can_pin) = self.can_pin {
            properties.push(("can-pin", can_pin));
        }
        if let Some(ref can_close) = self.can_close {
            properties.push(("can-close", can_close));
        }
        if let Some(ref page) = self.page {
            properties.push(("page", page));
        }
        if let Some(ref menu) = self.menu {
            properties.push(("menu", menu));
        }
        if let Some(ref actions) = self.actions {
            properties.push(("actions", actions));
        }
        if let Some(ref child) = self.child {
            properties.push(("child", child));
        }
        if let Some(ref can_focus) = self.can_focus {
            properties.push(("can-focus", can_focus));
        }
        if let Some(ref can_target) = self.can_target {
            properties.push(("can-target", can_target));
        }
        if let Some(ref css_classes) = self.css_classes {
            properties.push(("css-classes", css_classes));
        }
        if let Some(ref css_name) = self.css_name {
            properties.push(("css-name", css_name));
        }
        if let Some(ref focus_on_click) = self.focus_on_click {
            properties.push(("focus-on-click", focus_on_click));
        }
        if let Some(ref focusable) = self.focusable {
            properties.push(("focusable", focusable));
        }
        if let Some(ref halign) = self.halign {
            properties.push(("halign", halign));
        }
        if let Some(ref has_tooltip) = self.has_tooltip {
            properties.push(("has-tooltip", has_tooltip));
        }
        if let Some(ref height_request) = self.height_request {
            properties.push(("height-request", height_request));
        }
        if let Some(ref hexpand) = self.hexpand {
            properties.push(("hexpand", hexpand));
        }
        if let Some(ref hexpand_set) = self.hexpand_set {
            properties.push(("hexpand-set", hexpand_set));
        }
        if let Some(ref margin_bottom) = self.margin_bottom {
            properties.push(("margin-bottom", margin_bottom));
        }
        if let Some(ref margin_end) = self.margin_end {
            properties.push(("margin-end", margin_end));
        }
        if let Some(ref margin_start) = self.margin_start {
            properties.push(("margin-start", margin_start));
        }
        if let Some(ref margin_top) = self.margin_top {
            properties.push(("margin-top", margin_top));
        }
        if let Some(ref name) = self.name {
            properties.push(("name", name));
        }
        if let Some(ref opacity) = self.opacity {
            properties.push(("opacity", opacity));
        }
        if let Some(ref receives_default) = self.receives_default {
            properties.push(("receives-default", receives_default));
        }
        if let Some(ref sensitive) = self.sensitive {
            properties.push(("sensitive", sensitive));
        }
        if let Some(ref tooltip_markup) = self.tooltip_markup {
            properties.push(("tooltip-markup", tooltip_markup));
        }
        if let Some(ref tooltip_text) = self.tooltip_text {
            properties.push(("tooltip-text", tooltip_text));
        }
        if let Some(ref valign) = self.valign {
            properties.push(("valign", valign));
        }
        if let Some(ref vexpand) = self.vexpand {
            properties.push(("vexpand", vexpand));
        }
        if let Some(ref vexpand_set) = self.vexpand_set {
            properties.push(("vexpand-set", vexpand_set));
        }
        if let Some(ref visible) = self.visible {
            properties.push(("visible", visible));
        }
        if let Some(ref width_request) = self.width_request {
            properties.push(("width-request", width_request));
        }
        glib::Object::new::<Tab>(&properties)
    }

    pub fn label(mut self, label: &str) -> Self {
        self.label = Some(label.to_string());
        self
    }

    pub fn tooltip(mut self, tooltip: &str) -> Self {
        self.tooltip = Some(tooltip.to_string());
        self
    }

    pub fn pinned(mut self, pinned: bool) -> Self {
        self.pinned = Some(pinned);
        self
    }

    pub fn can_pin(mut self, can_pin: bool) -> Self {
        self.can_pin = Some(can_pin);
        self
    }

    pub fn can_close(mut self, can_close: bool) -> Self {
        self.can_close = Some(can_close);
        self
    }

    pub fn page(mut self, page: &impl IsA<gtk::Widget>) -> Self {
        self.page = Some(page.clone().upcast());
        self
    }

    pub fn menu(mut self, menu: &gio::Menu) -> Self {
        self.menu = Some(menu.clone());
        self
    }

    pub fn actions(mut self, actions: &impl IsA<gio::SimpleActionGroup>) -> Self {
        self.actions = Some(actions.clone().upcast());
        self
    }

    pub fn child(mut self, child: &impl IsA<gtk::Widget>) -> Self {
        self.child = Some(child.clone().upcast());
        self
    }

    pub fn can_focus(mut self, can_focus: bool) -> Self {
        self.can_focus = Some(can_focus);
        self
    }

    pub fn can_target(mut self, can_target: bool) -> Self {
        self.can_target = Some(can_target);
        self
    }

    pub fn css_classes(mut self, css_classes: Vec<String>) -> Self {
        self.css_classes = Some(css_classes);
        self
    }

    pub fn css_name(mut self, css_name: &str) -> Self {
        self.css_name = Some(css_name.to_string());
        self
    }

    pub fn focus_on_click(mut self, focus_on_click: bool) -> Self {
        self.focus_on_click = Some(focus_on_click);
        self
    }

    pub fn focusable(mut self, focusable: bool) -> Self {
        self.focusable = Some(focusable);
        self
    }

    pub fn halign(mut self, halign: gtk::Align) -> Self {
        self.halign = Some(halign);
        self
    }

    pub fn has_tooltip(mut self, has_tooltip: bool) -> Self {
        self.has_tooltip = Some(has_tooltip);
        self
    }

    pub fn height_request(mut self, height_request: i32) -> Self {
        self.height_request = Some(height_request);
        self
    }

    pub fn hexpand(mut self, hexpand: bool) -> Self {
        self.hexpand = Some(hexpand);
        self
    }

    pub fn hexpand_set(mut self, hexpand_set: bool) -> Self {
        self.hexpand_set = Some(hexpand_set);
        self
    }

    pub fn margin_bottom(mut self, margin_bottom: i32) -> Self {
        self.margin_bottom = Some(margin_bottom);
        self
    }

    pub fn margin_end(mut self, margin_end: i32) -> Self {
        self.margin_end = Some(margin_end);
        self
    }

    pub fn margin_start(mut self, margin_start: i32) -> Self {
        self.margin_start = Some(margin_start);
        self
    }

    pub fn margin_top(mut self, margin_top: i32) -> Self {
        self.margin_top = Some(margin_top);
        self
    }

    pub fn name(mut self, name: &str) -> Self {
        self.name = Some(name.to_string());
        self
    }

    pub fn opacity(mut self, opacity: f64) -> Self {
        self.opacity = Some(opacity);
        self
    }

    pub fn receives_default(mut self, receives_default: bool) -> Self {
        self.receives_default = Some(receives_default);
        self
    }

    pub fn sensitive(mut self, sensitive: bool) -> Self {
        self.sensitive = Some(sensitive);
        self
    }

    pub fn tooltip_markup(mut self, tooltip_markup: &str) -> Self {
        self.tooltip_markup = Some(tooltip_markup.to_string());
        self
    }

    pub fn tooltip_text(mut self, tooltip_text: &str) -> Self {
        self.tooltip_text = Some(tooltip_text.to_string());
        self
    }

    pub fn valign(mut self, valign: gtk::Align) -> Self {
        self.valign = Some(valign);
        self
    }

    pub fn vexpand(mut self, vexpand: bool) -> Self {
        self.vexpand = Some(vexpand);
        self
    }

    pub fn vexpand_set(mut self, vexpand_set: bool) -> Self {
        self.vexpand_set = Some(vexpand_set);
        self
    }

    pub fn visible(mut self, visible: bool) -> Self {
        self.visible = Some(visible);
        self
    }

    pub fn width_request(mut self, width_request: i32) -> Self {
        self.width_request = Some(width_request);
        self
    }
}

pub trait TabExt: 'static {
    #[doc(alias = "he_tab_get_label")]
    #[doc(alias = "get_label")]
    fn label(&self) -> glib::GString;

    #[doc(alias = "he_tab_set_label")]
    fn set_label(&self, value: &str);

    #[doc(alias = "he_tab_set_tooltip")]
    fn set_tooltip(&self, value: &str);

    #[doc(alias = "he_tab_get_pinned")]
    #[doc(alias = "get_pinned")]
    fn is_pinned(&self) -> bool;

    #[doc(alias = "he_tab_set_pinned")]
    fn set_pinned(&self, value: bool);

    #[doc(alias = "he_tab_get_can_pin")]
    #[doc(alias = "get_can_pin")]
    fn can_pin(&self) -> bool;

    #[doc(alias = "he_tab_set_can_pin")]
    fn set_can_pin(&self, value: bool);

    #[doc(alias = "he_tab_get_can_close")]
    #[doc(alias = "get_can_close")]
    fn can_close(&self) -> bool;

    #[doc(alias = "he_tab_set_can_close")]
    fn set_can_close(&self, value: bool);

    #[doc(alias = "he_tab_get_page")]
    #[doc(alias = "get_page")]
    fn page(&self) -> gtk::Widget;

    #[doc(alias = "he_tab_set_page")]
    fn set_page(&self, value: &impl IsA<gtk::Widget>);

    #[doc(alias = "he_tab_get_menu")]
    #[doc(alias = "get_menu")]
    fn menu(&self) -> gio::Menu;

    #[doc(alias = "he_tab_get_actions")]
    #[doc(alias = "get_actions")]
    fn actions(&self) -> gio::SimpleActionGroup;

    fn set_menu(&self, menu: Option<&gio::Menu>);

    #[doc(alias = "label")]
    fn connect_label_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "tooltip")]
    fn connect_tooltip_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "pinned")]
    fn connect_pinned_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "can-pin")]
    fn connect_can_pin_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "can-close")]
    fn connect_can_close_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "page")]
    fn connect_page_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "menu")]
    fn connect_menu_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<Tab>> TabExt for O {
    fn label(&self) -> glib::GString {
        unsafe { from_glib_none(ffi::he_tab_get_label(self.as_ref().to_glib_none().0)) }
    }

    fn set_label(&self, value: &str) {
        unsafe {
            ffi::he_tab_set_label(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_tooltip(&self, value: &str) {
        unsafe {
            ffi::he_tab_set_tooltip(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn is_pinned(&self) -> bool {
        unsafe { from_glib(ffi::he_tab_get_pinned(self.as_ref().to_glib_none().0)) }
    }

    fn set_pinned(&self, value: bool) {
        unsafe {
            ffi::he_tab_set_pinned(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    fn can_pin(&self) -> bool {
        unsafe { from_glib(ffi::he_tab_get_can_pin(self.as_ref().to_glib_none().0)) }
    }

    fn set_can_pin(&self, value: bool) {
        unsafe {
            ffi::he_tab_set_can_pin(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    fn can_close(&self) -> bool {
        unsafe { from_glib(ffi::he_tab_get_can_close(self.as_ref().to_glib_none().0)) }
    }

    fn set_can_close(&self, value: bool) {
        unsafe {
            ffi::he_tab_set_can_close(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    fn page(&self) -> gtk::Widget {
        unsafe { from_glib_none(ffi::he_tab_get_page(self.as_ref().to_glib_none().0)) }
    }

    fn set_page(&self, value: &impl IsA<gtk::Widget>) {
        unsafe {
            ffi::he_tab_set_page(
                self.as_ref().to_glib_none().0,
                value.as_ref().to_glib_none().0,
            );
        }
    }

    fn menu(&self) -> gio::Menu {
        unsafe { from_glib_none(ffi::he_tab_get_menu(self.as_ref().to_glib_none().0)) }
    }

    fn actions(&self) -> gio::SimpleActionGroup {
        unsafe { from_glib_none(ffi::he_tab_get_actions(self.as_ref().to_glib_none().0)) }
    }

    fn set_menu(&self, menu: Option<&gio::Menu>) {
        glib::ObjectExt::set_property(self.as_ref(), "menu", &menu)
    }

    fn connect_label_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_label_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::label\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_label_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_tooltip_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_tooltip_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::tooltip\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_tooltip_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_pinned_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_pinned_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::pinned\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_pinned_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_can_pin_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_pin_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::can-pin\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_can_pin_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_can_close_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_can_close_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::can-close\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_can_close_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_page_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_page_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::page\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_page_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_menu_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_menu_trampoline<P: IsA<Tab>, F: Fn(&P) + 'static>(
            this: *mut ffi::HeTab,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Tab::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::menu\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_menu_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for Tab {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Tab")
    }
}
