[external_libraries]
Gio = {min_version = "2.66"}

[options]
girs_directories = ["../gir-files", "../"]
library = "He"
version = "1"
min_cfg_version = "1"
target_path = "."
use_gi_docgen = true
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true
trust_return_value_nullability = true

external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gtk",
   "Pango",
]

generate = [
  "He.Avatar",
  "He.ColorRGBColor",
  "He.ColorXYZColor",
  "He.ColorLCHColor",
  "He.Colors",
  "He.DesktopDarkModeStrength",
  "He.Bin",
  "He.Button",
  "He.ButtonContent",
  "He.Window",
  "He.DesktopColorScheme",
  "He.AboutWindow",
  "He.AboutWindowLicenses",
  "He.AppBar",
  "He.ApplicationWindow",
  "He.Badge",
  "He.Banner",
  "He.BannerStyle",
  "He.BottomBar",
  "He.IconicButton",
  "He.BottomBarPosition",
  "He.Chip",
  "He.ContentBlock",
  "He.ContentBlockImage",
  "He.ContentBlockImageCluster",
  "He.ContentBlockImageClusterImagePosition",
  "He.ContentList",
  "He.TextButton",
  "He.Dialog",
  "He.TintButton",
  "He.FillButton",
  "He.DisclosureButton",
  "He.PillButton",
  "He.EmptyPage",
  "He.MiniContentBlock",
  "He.ModifierBadge",
  "He.ModifierBadgeAlignment",
  "He.NavigationRail",
  "He.OutlineButton",
  "He.OverlayButtonSize",
  "He.OverlayButton",
  "He.OverlayButtonAlignment",
  "He.SettingsPage",
  "He.SettingsWindow",
  "He.SettingsRow",
  "He.SettingsList",
  "He.SideBar",
  "He.Tab",
  "He.TabPage",
  "He.TabSwitcher",
  "He.TabSwitcherTabBarBehavior",
  "He.Toast",
  "He.ViewAux",
  "He.View",
  "He.ViewDual",
  "He.ViewMono",
  "He.ViewSubTitle",
  "He.ViewSwitcher",
  "He.ViewTitle",
  "He.ViewChooser",
  "He.WelcomeScreen",
  "He.SegmentedButton",
  "He.DesktopEnsorScheme",
  "He.ChipGroup",
  "He.DatePicker",
  "He.OverlayButtonTypeButton",
  "He.SwitchBar",
  "He.TimePicker",
  "He.Divider",
  "He.NavigationSection",
  "He.Slider",
  "He.TextField"
]

manual = [
  "Gtk.ApplicationWindow",
  "Gtk.Application",
  "Gtk.Orientation",
  "Gtk.ListBoxRow",
  "Gio.Application",
  "Gio.ActionGroup",
  "Gio.ActionMap",
  "Gio.ApplicationFlags",
  "Gtk.Widget",
  "Gtk.Accessible",
  "Gtk.Buildable",
  "Gtk.ConstraintTarget",
  "Gtk.Button",
  "Gtk.Actionable",
  "Gtk.Window",
  "Gtk.Native",
  "Gtk.Root",
  "Gtk.ShortcutManager",
  "Gtk.Stack",
  "GObject.Object",
  "GObject.ParamSpec",
  "GObject.Value",
  "Gtk.ScrolledWindow",
  "Gtk.Builder",
  "Gio.MenuModel",
  "Gio.Icon",
  "Gdk.Paintable",
  "Gio.Menu",
  "Gio.SimpleActionGroup",
  "GObject.BoxedCopyFunc",
  "GLib.DestroyNotify",
  "Gdk.RGBA",
  "Gtk.Align",
  "GLib.Variant",
  "Gtk.ToggleButton",
  "Gtk.Entry",
  "Gtk.CellEditable",
  "Gtk.Editable",
  "Gtk.Box",
  "Gtk.Orientable",
  "Gtk.Text",
  "GLib.DateTime",
  "Gtk.SingleSelection",
  "Gio.AsyncResult",
  "Gio.AsyncReadyCallback",
  "GLib.HashTable"
]

[[object]]
name = "He.Application"
status = "generate"
builder_postprocess = "Application::register_startup_hook(&ret);"
trait_name = "HeApplicationExt"
    [[object.function]]
    name = "new"
    manual = true
    [[object.function]]
    name = "set_default_accent_color"
    manual = true

[[object]]
name = "He.Desktop"
status = "generate"
    [[object.function]]
    name = "set_accent_color"
    ignore = true
