name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora-minimal:40
    steps:
      - name: Install required packages
        run: |
          dnf install -y --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' --setopt='terra.gpgkey=https://repos.fyralabs.com/terra$releasever/key.asc' terra-release
          dnf install -y libhelium libbismuth sass git

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: rustfmt, clippy

      - name: Generate docs
        run: cargo install rustdoc-stripper
      - run: ./generator.py --embed-docs
      - run: cargo doc --no-deps
      - run: mv target/doc/ docs

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
